# Конфигурация приложения

user:
  login: "admin"
  password: "admin123"


http_server:
  address: "localhost:8080"
  idle_timeout: 60s
  timeout: 4s


postgresql:
  host: "localhost"
  port: 5432
  user: "ivan"
  password: ""
  dbname: "mydb"
  sslmode: "disable"